# -*- coding: utf-8 -*-
"""24_09_02_hello_world01 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/hwan3326/2024-09-cpf-mon/blob/main/24_09_02_hello_world01%20(1).ipynb
"""

print("Hello World")

